import { Category } from './models/Category';
import { Article } from './models/Article';
import { Comment } from './models/Comment';

export const CATEGORIES: Category[] = [
  { id: 0, name: 'Hírek', color: '#EFB700', iconUrl: 'assets/images/system/nf-news.png' },
  { id: 1, name: 'PC', color: '#AF3DB1', iconUrl: 'assets/images/system/nf-pc.png' },
  { id: 2, name: 'Xbox', color: '#0CAB01', iconUrl: 'assets/images/system/nf-xbox.png' },
  { id: 3, name: 'PS', color: '#0067F3', iconUrl: 'assets/images/system/nf-ps.png' },
  { id: 4, name: 'Switch', color: '#F80000', iconUrl: 'assets/images/system/nf-switch.png' }
];

export const COMMENTS: Comment[] = [
  { id: 0, sender: 'Balázs', date: '2020. 04. 29.', body: 'Nisi id elementum quisque neque eu. S amet in risus sem venenatis. Egestas felis malesuada enim sit en.', article: 0},
  { id: 1, sender: 'Enikő', date: '2020. 04. 20.', body: 'Nirisus sem venenatis. Egestas felis malesuada enim sit en.', article: 1},
  { id: 2, sender: 'Sanyi', date: '2020. 04. 19.', body: 'Nirisus sem venenatis. Egestas felis malesuada enim sit en.', article: 0},
];

export const ARTICLES: Article[] = [
  { id: 0, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[3], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Nisi id elementum quisque neque eu. Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim. Diam habitant erat faucibus sagittis blandit pulvinar magna. Aenean id sed nulla dictum fermentum et nibh. Vulputate orci velit, facilisi viverra. Enim adipiscing pretium, lectus auctor nisl sodales mauris elementum. Ut purus tempus ipsum porttitor porttitor. Mattis ultrices nulla fermentum facilisis risus faucibus. Dolor amet quam eget bibendum a augue.\n\n Lectus eget nulla dui quam dui, in nibh lacus. Eget aliquam ullamcorper leo aliquet quis blandit dictum ut. Faucibus integer augue sit sed ultrices. Nunc nunc, suspendisse arcu, vel et. Mattis elit cursus et scelerisque lorem. Sit justo, massa velit dictum. Libero urna amet metus quis. Mattis amet neque sit congue semper integer quis porttitor. Etiam varius malesuada in luctus mattis nunc amet arcu sit. Est id nunc malesuada justo, ut. Pharetra, nisl urna porta lacus sollicitudin. Interdum id sollicitudin amet facilisi quisque aliquet duis quis. Non sit rhoncus, tortor sed hac amet at. Ut porta lacinia pellentesque lorem. Pellentesque at dictumst morbi quis praesent. Egestas suscipit mattis egestas viverra sit lectus. Id pulvinar orci mi et tincidunt tempor massa in convallis. Urna ut augue consequat eget eget ac. Euismod in leo est, sit eu, tincidunt. Odio elit quam mi eget consectetur. Donec fusce in morbi maecenas natoque augue vel volutpat ac. Condimentum ante quis integer morbi elementum, nulla ipsum posuere semper. Leo, volutpat turpis est netus tincidunt. Massa eget proin augue sit quisque. Laoreet lorem non urna, urna, vel mauris sodales duis. Fames sapien pharetra morbi scelerisque ac ridiculus dolor lectus ornare. Convallis ipsum proin malesuada ultricies varius consequat egestas. Molestie odio risus cras odio et dictum consectetur senectus. At aliquet dolor consectetur gravida tellus. Eget venenatis lectus eget cursus. At at congue at sem diam diam orci egestas diam. Nulla libero non morbi accumsan sit erat vestibulum libero. Nulla ac ut varius nibh. Duis faucibus nec magna vitae lectus feugiat blandit risus. Magna et aliquam scelerisque sit cursus ornare arcu aliquam facilisis. Mauris tincidunt etiam nisi, molestie cursus. Ornare bibendum mi dolor malesuada.", date: "tegnap"},
  { id: 1, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[2], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 2, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[4], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 3, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[0], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 4, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[0], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 5, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[0], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 6, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[3], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 7, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[3], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 8, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[4], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 9, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[2], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 10, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[1], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 11, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[1], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 12, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[1], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 13, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[1], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
  { id: 14, name: 'Sem tristique eleifend nulla. Porta placerat.', category: CATEGORIES[4], leadImageUrl: 'assets/images/articles/header-image.jpg', body: "Sit mus venenatis pellentesque quisque tellus sem tristique eleifend nulla. Porta placerat viverra pellentesque ullamcorper eget pellentesque. Scelerisque pulvinar proin morbi in id mollis nec pharetra, dictum. Interdum eros nam viverra malesuada pellentesque consectetur consectetur facilisi. Commodo mauris egestas cursus amet in risus sem venenatis. Egestas felis malesuada enim sit enim.", date: "2020. 04. 22."},
];